export const ReservationDefaultStates = {

    //Response from order API
    orderAccepted: false,

    //Seats avaiable
    seatsAvaiable: 0,

    //Seats price
    seatsPrice: 15,
    priceToShow: 0,

    //Options styles
    confirmSelected: 'div-seleccionado',
    showConfirmPanel: true,
    selectSelected: 'select-div',
    showSelectPanel: false,
    paymentSelected: 'payment-div',
    showPaymentPanel: false,
    summarySelected: 'summary-div',
    showSummary: false,
    getSelected: 'get-div',
    showGetButton: false,

    //Notifications modal
    ModalMessage: 'Welcome to the reservation panel!',
    ModalType: 0,

    //Reservation Big Form
    //Pick Venue
    venue: '',

    //Pick Day
    day: '',

    //Date
    date: '',

    //Seats Selected
    seatsSelected: [],

    //PaymentMethod
    paymentMethod: '',

    //Styles
    //Pick venue
    pickVenuePalermoInputClass: 'pick-venue-input-empty',
    pickVenueBelgranoInputClass: 'pick-venue-input-empty',
    pickVenueNunezInputClass: 'pick-venue-input-empty',

    //Set date
    fourteenInput: 'pick-time-input-empty',
    eighteenInput: 'pick-time-input-empty',
    twentytwoInput: 'pick-time-input-empty',
    oneInput: 'pick-time-input-empty',

    //Seats classes by default
    seatClass: 'seat',

    //Seats confirmation
    confirmSeatButtonClass: 'seat-confirm-button',

    //Seats
    seats: new Map(),
    //A Sector
    a1: 'seat',
    b1: 'seat',
    b2: 'seat',
    c1: 'seat',
    c2: 'seat',
    c3: 'seat',
    d1: 'seat',
    d2: 'seat',
    d3: 'seat',
    d4: 'seat',
    e1: 'seat',
    e2: 'seat',
    e3: 'seat',
    e4: 'seat',
    e5: 'seat',
    f1: 'seat',
    f2: 'seat',
    f3: 'seat',
    f4: 'seat',
    f5: 'seat',
    f6: 'seat',
    g1: 'seat',
    g2: 'seat',
    g3: 'seat',
    g4: 'seat',
    g5: 'seat',
    g6: 'seat',
    h1: 'seat',
    h2: 'seat',
    h3: 'seat',
    h4: 'seat',
    h5: 'seat',
    h6: 'seat',
    h7: 'seat',

    //Sector B
    a2: 'seat',
    a3: 'seat',
    a4: 'seat',
    a5: 'seat',
    a6: 'seat',
    a7: 'seat',
    a8: 'seat',
    a9: 'seat',
    a10: 'seat',
    a11: 'seat',
    a12: 'seat',
    b3: 'seat',
    b4: 'seat',
    b5: 'seat',
    b6: 'seat',
    b7: 'seat',
    b8: 'seat',
    b9: 'seat',
    b10: 'seat',
    b11: 'seat',
    b12: 'seat',
    c4: 'seat',
    c5: 'seat',
    c6: 'seat',
    c7: 'seat',
    c8: 'seat',
    c9: 'seat',
    c10: 'seat',
    c11: 'seat',
    c12: 'seat',
    c13: 'seat',
    d5: 'seat',
    d6: 'seat',
    d7: 'seat',
    d8: 'seat',
    d9: 'seat',
    d10: 'seat',
    d11: 'seat',
    d12: 'seat',
    d13: 'seat',
    d14: 'seat',
    e6: 'seat',
    e7: 'seat',
    e8: 'seat',
    e9: 'seat',
    e10: 'seat',
    e11: 'seat',
    e12: 'seat',
    e13: 'seat',
    e14: 'seat',
    e15: 'seat',
    f7: 'seat',
    f8: 'seat',
    f9: 'seat',
    f10: 'seat',
    f11: 'seat',
    f12: 'seat',
    f13: 'seat',
    f14: 'seat',
    f15: 'seat',
    f16: 'seat',
    f17: 'seat',
    g7: 'seat',
    g8: 'seat',
    g9: 'seat',
    g10: 'seat',
    g11: 'seat',
    g12: 'seat',
    g13: 'seat',
    g14: 'seat',
    g15: 'seat',
    g16: 'seat',
    h8: 'seat',
    h9: 'seat',
    h10: 'seat',
    h11: 'seat',
    h12: 'seat',
    h13: 'seat',
    h14: 'seat',
    h15: 'seat',
    h16: 'seat',
    h17: 'seat',

    //Sector C
    a13: 'seat',
    b13: 'seat',
    b14: 'seat',
    c14: 'seat',
    c15: 'seat',
    c16: 'seat',
    d15: 'seat',
    d16: 'seat',
    d17: 'seat',
    d18: 'seat',
    e16: 'seat',
    e17: 'seat',
    e18: 'seat',
    e19: 'seat',
    e20: 'seat',
    f18: 'seat',
    f19: 'seat',
    f20: 'seat',
    f21: 'seat',
    f22: 'seat',
    f23: 'seat',
    g17: 'seat',
    g18: 'seat',
    g19: 'seat',
    g20: 'seat',
    g21: 'seat',
    g22: 'seat',
    h18: 'seat',
    h19: 'seat',
    h20: 'seat',
    h21: 'seat',
    h22: 'seat',
    h23: 'seat',
    h24: 'seat',

}